default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root

development:
  <<: *default
  database: punchy_development

test:
  <<: *default
  database: punchy_test


production:
  url: "mysql2://t0pzo4mbdhw1k1j3:rbt5lc4yyceeazij@y06qcehxdtkegbeb.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/dsywob6emgvfo7jx"