default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root

development:
  <<: *default
  database: punchy_development

production:
  <<: *default
  database: punchy_production
  username: punchy
